import client from './client';
export const register = d => client.post('/auth/register/', d);
export const verifyEmail = d => client.post('/auth/verify-email/', d);
export const login = d => client.post('/auth/login/', d);
export const forgotPassword = d => client.post('/auth/forgot-password/', d);
export const resetPassword = d => client.post('/auth/reset-password/', d);
export const getMe = () => client.get('/auth/me/');
export const getAdminUsers = () => client.get('/auth/admin/users/');
export const toggleStaff = id => client.post(`/auth/admin/users/${id}/toggle-staff/`);
export const deleteUser = id => client.delete(`/auth/admin/users/${id}/delete/`);
export const updateProfile = d => client.patch('/auth/profile/update/', d);
export const changePassword = d => client.post('/auth/change-password/', d);
export const requestEmailChange = d => client.post('/auth/change-email/request/', d);
export const confirmEmailChange = d => client.post('/auth/change-email/confirm/', d);
export const resendVerification = () => client.post('/auth/resend-verification/');
